# This is an example Mocha config containing every Mocha option plus others
allow-uncaught: false
bail: false
color: true
diff: true
timeout: 5000 # same as "no-timeout: true" or "timeout: 0"
trace-warnings: true # node flags ok
ui: 'bdd'
v8-stack-trace-limit: 100 # V8 flags are prepended with "v8-"
watch-files:
  - 'test/**/*.spec.ts'
watch-ignore:
  - 'node_modules/**/*'
