#!/usr/bin/env bash

# This creates package.json in each build type (cjs and mjs) that specifies what type of module resolution is used in
# in the rest of the subtree. Eq. for /cjs subfolder it specifies that CommonJS is used in that subfolder and so on.
# Source: https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

cat >dist/cjs/package.json <<!EOF
{
    "type": "commonjs",
    "browser": {
     "readable-stream": false,
     "stream": false,
      "./utils/data.js": "./utils/data.browser.js",
      "./utils/collection.node.js": "./utils/collection.browser.js"
    }
}
!EOF

cat >dist/mjs/package.json <<!EOF
{
    "type": "module",
    "browser": {
     "readable-stream": false,
     "stream": false,
      "./utils/data.js": "./utils/data.browser.js",
      "./utils/collection.node.js": "./utils/collection.browser.js"
    }
}
!EOF
