#!/usr/bin/env bash

cat >dist/cjs/package.json <<!EOF
{
    "type": "commonjs",
    "browser": {
      "./utils/data.js": "./utils/data.browser.js",
      "./utils/collection.node.js": "./utils/collection.browser.js"
    }
}
!EOF

cat >dist/mjs/package.json <<!EOF
{
    "type": "module",
    "browser": {
      "./utils/data.js": "./utils/data.browser.js",
      "./utils/collection.node.js": "./utils/collection.browser.js"
    }
}
!EOF
