import { Binary } from 'cafe-utility'
import { MantarayNode } from '../../src'
import { arbitraryReference } from '../utils'

const ENCODER = new TextEncoder()

test('MantarayNode basic', () => {
  const node = new MantarayNode()
  node.addFork('foo', arbitraryReference())
  node.addFork('foobar', arbitraryReference())
  node.addFork('foobarbaz', arbitraryReference())
  node.addFork('fooxyz', arbitraryReference())
  expect(node.forks.size).toBe(1)
  expect(node.collect()).toHaveLength(4)

  expect(node.find('foo')).toHaveProperty('fullPath', ENCODER.encode('foo'))
  expect(node.find('foobar')).toHaveProperty('fullPath', ENCODER.encode('foobar'))
  expect(node.find('foobarbaz')).toHaveProperty('fullPathString', 'foobarbaz')
  expect(node.find('fooxyz')).toHaveProperty('fullPathString', 'fooxyz')

  const fooNode = node.find('foo')!
  expect(fooNode.path).toEqual(ENCODER.encode('foo'))
  expect(fooNode.forks.size).toBe(2)
  expect(fooNode.find('bar')).toBeTruthy()
  expect(fooNode.find('barbaz')).toBeTruthy()
  expect(fooNode.find('xyz')).toBeTruthy()

  const foobarNode = node.find('foobar')!
  expect(foobarNode.path).toEqual(ENCODER.encode('bar'))
  expect(foobarNode.forks.size).toBe(1)
  expect(foobarNode.find('baz')).toBeTruthy()

  const foobarbazNode = node.find('foobarbaz')!
  expect(foobarbazNode.path).toEqual(ENCODER.encode('baz'))
  expect(foobarbazNode.forks.size).toBe(0)

  node.removeFork('foobar')
  expect(node.find('foobar')).toBeNull()
  expect(node.find('foobarbaz')).toBeTruthy()
  expect(node.collect()).toHaveLength(3)

  node.removeFork('foobarbaz')
  expect(node.find('foobarbaz')).toBeNull()
  expect(node.collect()).toHaveLength(2)
})

test('directory node keeps its forks across a marshal/unmarshal round-trip', async () => {
  const node = new MantarayNode()
  node.addFork('/index.html', arbitraryReference())
  node.addFork('/about.html', arbitraryReference())

  const slash = node.forks.get('/'.charCodeAt(0))!.node
  expect(ENCODER.encode('/')).toEqual(slash.path)
  expect(slash.forks.size).toBe(2)

  const bytes = await slash.marshal()
  const restored = MantarayNode.unmarshalFromData(bytes, new Uint8Array(32))

  expect(restored.forks.size).toBe(2)
})

test('reads a Bee-produced v0.2 directory node (real reference vector)', async () => {
  // Generated by Bee's own mantaray MarshalBinary (bee/pkg/manifest/mantaray) for
  // a directory node ("/") with two value forks and a zero obfuscation key.
  // Byte 63 (the reference-size byte) is 0x20 = 32: Bee never emits 0 for a
  // directory node, which is exactly what marshal() must reproduce.
  const vector =
    '00000000000000000000000000000000000000000000000000000000000000005768b3b6a7db56d21d1abff40d41cebfc83448fed8d7e9b06ec0d3b073f28f2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000202000000000000000000000000000000000000020a61626f75742e68746d6c0000000000000000000000000000000000000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa020a696e6465782e68746d6c0000000000000000000000000000000000000000bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
  const data = Binary.hexToUint8Array(vector)

  expect(data[63]).toBe(32) // Bee's reference-size byte for this directory node

  const node = MantarayNode.unmarshalFromData(data, new Uint8Array(32))

  expect(node.forks.size).toBe(2)
  expect(node.forks.get('a'.charCodeAt(0))!.prefix).toEqual(ENCODER.encode('about.html'))
  expect(node.forks.get('i'.charCodeAt(0))!.prefix).toEqual(ENCODER.encode('index.html'))

  // An untouched node must re-marshal to the exact same bytes Bee produced,
  // including each fork's preserved type byte (0x02 = value).
  expect(await node.marshal()).toEqual(data)
})

test('MantarayNode long', () => {
  const htmlPath = '/Code/Swarm/bee-js/test/coverage/lcov-report/index.html'
  const jsPath = '/Code/Swarm/bee-js/test/coverage/lcov-report/index.js'
  const dsStorePath = '/Code/Swarm/bee-js/test/coverage/.DS_Store'

  const node = new MantarayNode()

  node.addFork(htmlPath, arbitraryReference())
  expect(node.collect()).toHaveLength(1)
  node.addFork(jsPath, arbitraryReference())
  expect(node.collect()).toHaveLength(2)
  node.addFork(dsStorePath, arbitraryReference())
  expect(node.collect()).toHaveLength(3)

  expect(node.find(htmlPath)).toHaveProperty('fullPathString', htmlPath)
  expect(node.find(jsPath)).toHaveProperty('fullPath', ENCODER.encode(jsPath))
  expect(node.find(dsStorePath)).toHaveProperty('fullPath', ENCODER.encode(dsStorePath))

  node.removeFork(dsStorePath)

  expect(node.find(htmlPath)).toHaveProperty('fullPath', ENCODER.encode(htmlPath))
  expect(node.find(jsPath)).toHaveProperty('fullPathString', jsPath)
  expect(node.find(dsStorePath)).toBeNull()
  expect(node.collect()).toHaveLength(2)
})
