name: Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm deps
        run: npm ci

      - name: Commit linting
        uses: wagoid/commitlint-github-action@v2

      - name: Code linting
        run: npm run lint:check
        env:
          CI: true

      - name: Dependency check
        run: npm run depcheck

      - name: Check typings
        run: npm run check:types

      - name: Check build
        run: npm run build

      - name: Trigger API Docs update PR
        uses: peter-evans/repository-dispatch@v1
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ethersphere/bee-js-docs
          event-type: trigger-api-docs-pr
