name: Update docs

on:
  push:
    branches:
      - 'master'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger API Docs update PR
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ethersphere/bee-js-docs
          event-type: trigger-api-docs-pr
